function omega = quaternion_omega_from_q_dot(Q, dQ_dt)
    % 从四元数Q和其一阶导数dQ_dt计算角速度向量omega
    % 公式：dQ/dt = 0.5 * [omega]× Q → 反解omega
    q0 = Q(1); q1 = Q(2); q2 = Q(3); q3 = Q(4);
    dq0 = dQ_dt(1); dq1 = dQ_dt(2); dq2 = dQ_dt(3); dq3 = dQ_dt(4);
    omega = 2 * [ ...
        dq1*q0 - dq0*q1 + dq3*q2 - dq2*q3; ...
        dq2*q0 - dq0*q2 + dq1*q3 - dq3*q1; ...
        dq3*q0 - dq0*q3 + dq2*q1 - dq1*q2  ...
    ];
end